// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1X4YwDbwzxsPGoxvM2Vcf48WXcbmpQm8',
    appId: '1:706122592652:web:327f9bf35f78c418cd66a9',
    messagingSenderId: '706122592652',
    projectId: 'infinity-miner',
    authDomain: 'infinity-miner.firebaseapp.com',
    storageBucket: 'infinity-miner.appspot.com',
    measurementId: 'G-20R49DE5HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX04izIrSCG-gpEOYetXpRzWoy5rL7hPU',
    appId: '1:706122592652:android:306a557a89122d19cd66a9',
    messagingSenderId: '706122592652',
    projectId: 'infinity-miner',
    storageBucket: 'infinity-miner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjsExPOZVxvF9pIdnISyq9o4THQFct9Y',
    appId: '1:706122592652:ios:dcbf749697ec64d3cd66a9',
    messagingSenderId: '706122592652',
    projectId: 'infinity-miner',
    storageBucket: 'infinity-miner.appspot.com',
    iosBundleId: 'com.example.infinityminer',
  );
}
